<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{a35327ac-fd04-0d62-2f0c-284f65227c3f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_ST();
//MAIN_LD();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="1" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>