<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ErrorTrack" Id="{b7d2262d-2290-026e-04de-e41a4d953470}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ErrorTrack IMPLEMENTS iTrack
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{eeff0d3e-8d73-0d64-379f-cf0d456afc19}" />
    <Folder Name="Properties" Id="{13bdc662-fc7c-04cc-21a6-3ca65662fecd}" />
    <Method Name="Cyclic" Id="{2f007afa-b200-03a3-0dc1-86e0ff4e5c17}" FolderPath="Methods\">
      <Declaration><![CDATA[METHOD Cyclic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[

ADSLOGSTR( ADSLOG_MSGTYPE_ERROR, 'The Track.Cyclic function was called on an error track.', '');]]></ST>
      </Implementation>
    </Method>
    <Property Name="Id" Id="{3f245ec6-2d35-0e07-007d-ee805d2b4910}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY Id : INT]]></Declaration>
      <Get Name="Get" Id="{8bf80f8b-c4c5-033d-3938-7faf2a4b2089}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[

ADSLOGSTR( ADSLOG_MSGTYPE_ERROR, 'The Track.Id get property is unavailable while the mover is activating a new track.', '');]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{08d650b4-e18a-001a-1529-9066b9b74657}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[

ADSLOGSTR( ADSLOG_MSGTYPE_ERROR, 'The Track.Id set property is unavailable while the mover is activating a new track.', '');]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="OTCID" Id="{ddf37bf7-b48a-0af3-260c-7b9e319896e8}" FolderPath="Properties\">
      <Declaration><![CDATA[PROPERTY OTCID : OTCID]]></Declaration>
      <Get Name="Get" Id="{c7411707-c9da-00e0-065a-2c6b4c6ba42b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[

ADSLOGSTR( ADSLOG_MSGTYPE_ERROR, 'The Track.OTCID get property is unavailable while the mover is activating a new track.', '');]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{de34ce6f-78eb-003b-21a4-99278d48bb7c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[

ADSLOGSTR( ADSLOG_MSGTYPE_ERROR, 'The Track.OTCID set property is unavailable while the mover is activating a new track.', '');]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="ErrorTrack">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="ErrorTrack.Cyclic">
      <LineId Id="6" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="ErrorTrack.Id.Get">
      <LineId Id="5" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="ErrorTrack.Id.Set">
      <LineId Id="5" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="ErrorTrack.OTCID.Get">
      <LineId Id="5" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="ErrorTrack.OTCID.Set">
      <LineId Id="5" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>