<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Mediator" Id="{164d51b4-07ec-0e46-0eb0-392af39d7d3a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Mediator
VAR_INPUT

	MoverArray		: ARRAY [0..GVL.NUM_MOVERS-1] OF POINTER TO Mover;
	StationArray	: ARRAY [0..GVL.NUM_MOVERS-1] OF POINTER TO Station;

END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Mediator">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>