<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Track" Id="{1d568bee-17b0-45d9-8c81-c6842c2a11d5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Track
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{39635f7a-3c34-4d67-b666-c6e08a70323b}" />
    <Folder Name="Properties" Id="{5266f954-d54f-4746-897a-a6f4b18b8998}" />
    <LineIds Name="Track">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>