site_name: XTS Base Documentation

theme:
    name: material
    logo: Images/XTS.svg
    custom_dir: docs/overrides
    font:
        text: Arial
    features:
        - navigation.tabs

extra_css:
    - style.css

use_directory_urls: false

repo_name: XTS Base Project GitHub
repo_url: https://github.com/Beckhoff-USA-Community/XTS_Base
edit_uri: ""

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets

nav:
    - Home: index.md
    - Getting Started:
            - Introduction:     GettingStarted/Introduction.md
            - First Steps:      GettingStarted/GettingStarted.md
            - Quick Tips:       GettingStarted/QuickTips.md
            - Visualization:    GettingStarted/Visualization.md
    - Code Reference:
        - Overview:             CodeReference/Objectives.md
        - Objects:
            - Mediator:             CodeReference/Objects/Mediator.md
            - Mover:                CodeReference/Objects/Mover.md
            - Mover List:           CodeReference/Objects/MoverList.md
            - Position Trigger:     CodeReference/Objects/PositionTrigger.md
            - Station:              CodeReference/Objects/Station.md
            - Track:                CodeReference/Objects/Track.md
            - Zone:                 CodeReference/Objects/Zone.md
        - Diagnostics:
            - Basics:           CodeReference/Diagnostics/Basics.md
            - ErrorMovers:      CodeReference/Diagnostics/ErrorMovers.md
            - Event Logger:     CodeReference/Diagnostics/EventLogger.md
            - Utility Library:  CodeReference/Diagnostics/UtilityLibrary.md
    - Examples:
        - Station to Station:   Examples/StationRouting.md
