site_name: XTS Base Documentation

theme:
    name: material
    logo: Images/XTS.svg
    custom_dir: docs/overrides
    font:
        text: Arial
    features:
        - navigation.tabs

extra_css:
    - style.css

use_directory_urls: false

repo_name: XTS Base Project GitHub
repo_url: https://github.com/Beckhoff-USA-Community/XTS_Base
edit_uri: ""

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets

nav:
    - Home: index.md
    - Getting Started:
            - 1. Introduction:              GettingStarted/1_Introduction.md
            - 2. First Steps:               GettingStarted/2_FirstSteps.md
            - 3. Design Approach:           GettingStarted/3_DesignApproach.md
            - 4. Project Tour:           GettingStarted/4_ProjectTour.md
            - 5. System Recovery:           GettingStarted/5_SystemRecovery.md
            - 6. Visualization:             GettingStarted/6_Visualization.md
            - 7. Tips & Recommendations:    GettingStarted/7_TipsRecommendations.md
    - Code Reference:
        - Objects:
            - Mover:                CodeReference/Objects/Mover.md
            - Mover List:           CodeReference/Objects/MoverList.md
            - Objective:            CodeReference/Objects/Objective.md
            - Position Trigger:     CodeReference/Objects/PositionTrigger.md
            - Station:              CodeReference/Objects/Station.md
            - Track:                CodeReference/Objects/Track.md
            - Zone:                 CodeReference/Objects/Zone.md
            - System:             CodeReference/Objects/Mediator.md
        - Diagnostics:
            - Basics:           CodeReference/Diagnostics/Basics.md
            - ErrorMovers:      CodeReference/Diagnostics/ErrorMovers.md
            - Event Logger:     CodeReference/Diagnostics/EventLogger.md
            - Mover Data:       CodeReference/Diagnostics/MoverData.md
            - Utility Library:  CodeReference/Diagnostics/UtilityLibrary.md
    - Examples:
        - Station to Station:   Examples/StationRouting.md
